config/routes.rb
NewspaperApp::Application.routes.draw do

  resources :newspapers
  resources :subscription_plans
  resources :users
  resource :sessions, :only => [:create, :destroy]

  get "sign_up" => "users#new"
  get "sign_in" => "sessions#new"
  get "sign_out" => "sessions#destroy"

end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
  attr_accessible :editor, :title, :subscription_plans_attributes
  has_many :subscription_plans, :inverse_of => :newspaper

  accepts_nested_attributes_for :subscription_plans

  validates :editor, :title, :presence => true
end

app/models/subscription_plan.rb
class SubscriptionPlan < ActiveRecord::Base
   attr_accessible :price, :weekly, :newspaper_id

   has_many :user_subscriptions
   has_many :users, :through => :user_subscriptions


   belongs_to :newspaper


   validates :price,  :newspaper, :presence => true
   validates :weekly, :inclusion => { :in => [true, false]}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :subscription_ids, :remember_token
  has_many :user_subscriptions, :inverse_of => :user
  has_many :subscriptions, :through => :user_subscriptions, :source =>
           :subscription_plan
  has_many :newspapers, :through => :subscriptions
end

app/models/user_subscription.rb
class UserSubscription < ActiveRecord::Base
  belongs_to :subscription_plan
  belongs_to :user

  validates :user, :subscription_plan, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery




end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController

  def new
    @newspaper = Newspaper.new
    @newspaper.subscription_plans.build
  end

  def show
    @newspaper = Newspaper.find(params[:id])

  end

  def create
    @newspaper = Newspaper.new(params[:newspaper])
    if @newspaper.save
      redirect_to newspaper_url(@newspaper)
    else
      render :new
    end

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create
    if params[:user][:password] == User.find_by_email(params[:user][:email]).password

      @user = User.find_by_email(params[:user][:email])
      log_in(@user)
      flash[:notice] = "Login successful"
      redirect_to @user
    else
      flash[:notice] = "Bad Log in Info, try again"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to sign_up_url
  end

end

app/controllers/subscription_plans_controller.rb
class SubscriptionPlansController < ApplicationController

  def new
    @subscription_plan = SubscriptionPlan.new
  end

  def show
    @subscription_plan = SubscriptionPlan.find(params[:id])
  end

  def create
    @subscription_plan = SubscriptionPlan.new(params[:subscription_plan])
    if @subscription_plan.save
      redirect_to @subscription_plan.newspaper
    else
      ## FLASH NOTICES HERE?
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    if current_user
      flash[:notice] = "Already signed in"
      redirect_to User.find_by_remember_token(session[:remember_token])
    else
      @user = User.new
      @user.subscriptions.build
    end
  end

  def show

    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if (params[:user][:password] == params[:confirmation]) && @user.save
      flash[:notice] = "Login successful"
      log_in(@user)
      redirect_to @user
    else
      flash[:notice] = @user.errors.full_messages.join
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/newspaper_helper.rb
module NewspaperHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    user.remember_token = SecureRandom.hex(8)
    session[:remember_token] = user.remember_token
    user.save!
  end

  def current_user
    if session[:remember_token]
      User.find_by_remember_token(session[:remember_token])
    end
  end

  def log_out
    if session[:remember_token]
      User.find_by_remember_token(session[:remember_token]).remember_token = nil
      session[:remember_token] = nil
    else
      flash[:notice] = "already logged out "
    end
  end

end

app/helpers/subscription_plans_helper.rb
module SubscriptionPlansHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewspaperApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <nav>
      <% if current_user  %>
      <%= link_to "sign out", sign_out_url %>
      <% else  %>
      <%= link_to "sign in", sign_in_url %>
      <% end %>
  </nav>
</head>
<body>
  <%= flash[:notice] %>
  <%= yield %>

</body>
</html>

app/views/newspapers/new.html.erb
<h1> Create a Newspaper </h1>
<%= form_for(@newspaper) do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :editor %>
<%= f.text_field :editor %>

<br>

<h4> Add a subscription plan below: </h4>
<%= f.fields_for(:subscription_plans) do |sub_form| %>

  <%= sub_form.label :price %>
  <%= sub_form.number_field :price %>
  <br>
  <%= sub_form.radio_button :weekly, true %>
  <%= sub_form.label :weekly, "Weekly", value: true %>
  <br>
  <%= sub_form.radio_button :weekly, false %>
  <%= sub_form.label :weekly, "Daily", value: false %>
  <br>
<% end %>

<%= f.submit %>

<% end %>

app/views/newspapers/show.html.erb
<h1> <%= @newspaper.title %> </h1>
<h4> by <%= @newspaper.editor %> </h4>

<p>
  <% @newspaper.subscription_plans.each do |plan| %>
    <li><%= "$#{plan.price} #{plan.weekly ? "weekly" : "daily"}" %></li>
  <% end %>

</p>

app/views/subscription_plans/new.html.erb
<h1> Create New Subscription Plan </h1>

<%= form_for(@subscription_plan) do |f| %>

  <%= f.label :price %>
  <%= f.number_field :price %>
  <br>
  <%= f.radio_button :weekly, true  %>
  <%= f.label :weekly, "Weekly", value: true %>
  <br>
  <%= f.radio_button :weekly, false  %>
  <%= f.label :weekly, "Daily", value: false %>
  <br>
  <%= f.label :newspaper_id, "Select a newspaper:" %>
  <%= f.collection_select :newspaper_id, Newspaper.all, :id, :title %>
  <br>
  <%= f.submit %>

<% end %>

app/views/subscription_plans/show.html.erb
<h1><%= @subscription_plan.inspect %></h1>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_for @user do |f| %>

<%= f.label :email %>
<%= f.text_field :email %>
<br>
<%= f.label :password %>
<%= f.password_field :password %>
<br>
<%= label_tag("confirmation", "Confirm Pwd:") %>
<%= password_field_tag("confirmation") %>

<br>

<h3>Choose a package </h3>
<%= f.fields_for(:subscriptions) do |sub_form| %>

<table>
<% SubscriptionPlan.all.each do |subscription| %>
  <tr>
    <td>
       <%=
          check_box_tag(
          "user[subscription_ids][]",
          subscription.id,
          @user.subscription_ids.include?(subscription.id),
          :id => "subscription[subscription.id]"
        )
        %>
        <%= label_tag("subscription[subscription.id]", subscription.newspaper.title) %>
        <br>
        <td> <%= number_to_currency(subscription.price) %> </td>
        <td> <%= subscription.weekly ? "weekly" : "daily" %> </td>
    </td>
        <% end %>

    <%= hidden_field_tag("user[subscription_ids][]") %>


    <br>
  </tr>
<% end %>

</table>




<%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h2> Welcome </h2>

<h3> Choose Subscription Plans </h3>

<%= form_for(@user) do |f| %>

  <% SubscriptionPlan.all.each do |subscription| %>
    <%=
    check_box_tag(
    "user[subscription_ids][]",
    subscription.id,
    @user.subscription_ids.include?(subscription.id),
    :id => "subscription_#{subscription.id}"
    )
    %>
    <%= label_tag("subscription_#{subscription.id}", subscription.newspaper.title) %>
    <%= hidden_field_tag("user[subscription_ids][]") %>

    <% end %>

<%= f.submit %>
<% end %>